<div class="header-line">
    <div class="size-wrap">
        <div class="header-line-title title-white">Phalcon API</div>
    </div>
</div>


<div class="size-wrap">

<div class="note">Phalcon's documentation is maintained in <a href="#">Github repositories</a>. You are more than welcome to send us pull requests if you found an error or if</div>

<ul class="tabs clear-fix">
    <li><a class="tab-link" href="#"><u>Overview</u></a></li>
    <li><a class="tab-link active" href="#"><u>API Reference</u></a></li>
</ul>

<div class="content-wrap clear-fix">

<div class="sidebar">

    <div class="searchbox-wrap">
        <input type="text" name="q" id="searchbox" class="searchbox" placeholder="Search"/>
        <input type="submit" class="search-button"/>
    </div>


    <ul class="api-table-of-contents" id="class-tree">

        <?php foreach ( $tree as $root => $rootChildrens ): ?>
            <li>
                <a href="#<?php echo $root; ?>" class="api-top-level-link"><?php echo $root; ?></a>

                <?php if ( count($rootChildrens)!=0 ): ?>

                    <ul class="api-sublist dash-list">
                        <?php foreach ( $rootChildrens as $rootChildren => $childChildrens ): ?>
                            <li>
                                <a class="api-link active" href="#<?php echo $rootChildren ?>"><?php echo $rootChildren ?></a>

                                <?php if ( count($childChildrens)!=0 ): ?>

                                    <ul class="api-sublist">
                                        <?php foreach ( $childChildrens as $lastChildren=>$v ): ?>
                                            <li><a href="#" class="api-link"><?php echo $lastChildren ?></a></li>
                                        <?php endforeach ?>
                                    </ul>

                                <?php endif ?>

                            </li>
                        <?php endforeach ?>
                    </ul>

                <?php endif ?>

            </li>
        <?php endforeach ?>

    </ul>
</div>

<div class="content">

    <h1><span class="lighter"><?php echo $classData['type'] ?></span> <?php echo $classData['name'] ?></h1>

    <table class="api-info-table">

        <tr>
            <th id="Namespace">Namespace:</th>
            <td><a href="#"><?php echo $classData['namespace'] ?></a></td>
        </tr>


        <?php if ( $classData['extends'] ): ?>
            <tr>
                <th id="Extends">Extends:</th>
                <td><a href="#"><?php echo $classData['extends'] ?></a></td>
            </tr>
        <?php endif ?>

        <?php if ( $classData['implements'] ): ?>
            <tr>
                <th id="Implements">Implements:</th>
                <td>
                    <?php foreach ( $classData['implements'] as $implements ): ?>
                        <a href="#"><?php echo $implements ?></a>,
                    <?php endforeach ?>
                </td>
            </tr>
        <?php endif ?>

    </table>

    <?php if ( $classData['description'] ): ?>
        <div class="note"><?php echo $classData['description']['description'] ?></div>
    <?php endif ?>

    <!--
            <h2>Subclasses</h2>

            <ul class="two-columns">
                <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Apc</span></a></li>
                <li><a href="#">Phalcon\Cache\Backend\<span class="strong">File</span></a></li>
                <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Memcache</span></a></li>
                <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Memory</span></a></li>
                <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Mongo</span></a></li>
            </ul>
    -->
    <?php if ( $classData['constants'] ): ?>

        <h2 id="Constants">Constants</h2>

        <ul class="two-columns">
            <?php foreach ( $classData['constants'] as $value => $type ): ?>
                <li><?php echo gettype($type) . ' ' . $value ?></li>
            <?php endforeach ?>
        </ul>

    <?php endif ?>

    <?php if ( $classData['methods'] ): ?>

        <h2 id="summary">Methods summary</h2>

        <table class="api-methods-table">
            <?php foreach ( $classData['methods'] as $method ): ?>
                <tr>
                    <td class="method"><span class="method-type <?php echo implode(' ' , $method['modifiers']) ?>" data-tooltip="public"></span> <a
                            href="#<?php echo $method['name'] ?>"><?php echo $method['name'] ?></a></td>
                    <td class="description"><?php echo isset($method['description']['description_mini']) ? $method['description']['description_mini'] : '' ?></td>
                </tr>
            <?php endforeach ?>
        </table>

        <h2 id="details">Method details</h2>

        <?php foreach ( $classData['methods'] as $method ): ?>
            <br/>
            <span class="h3" id="<?php echo $method['name'] ?>"><?php echo $method['name']; ?></span>
            <?php if ( $method['inherited'] ): ?>
                inherited <?php echo $method['inherited'] ?>
            <?php endif ?>

            <p>
            <div class="highlight">
                <pre><?php echo implode(' ' , $method['modifiers']) ?> <?php echo $method['name'] ?> ( <?php echo implode(', ' , $method['parameters']) ?> )</pre>
            </div>
            </p>

            <?php if ( isset($method['description']['description']) ): ?>

                <p><?php echo $method['description']['description']; ?></p>

            <?php endif ?>

            <?php if ( $method['description']['params'] ): ?>

                <h4>Parameters:</h4>

                <ul>
                    <?php foreach ( $method['description']['params'] as $parameterName => $parameterType ): ?>
                        <li><span class="strong"><?php echo $parameterName ?></span> <a href="#"><?php echo $parameterType ?></a></li>
                    <?php endforeach ?>
                </ul>

            <?php endif ?>

            <?php if ( $method['description']['return'] !== 'return' ): ?>
                <h4>Returns:</h4>

                <p><?php echo $method['description']['return'] ?></p>
            <?php endif ?>

        <?php endforeach ?>

    <?php endif ?>
</div>
</div>
