<div class="header-line">
    <div class="size-wrap">
        <div class="header-line-title title-white">Phalcon API</div>
    </div>
</div>


<div class="size-wrap">

<div class="note">Phalcon's documentation is maintained in <a href="#">Github repositories</a>. You are more than welcome to send us pull requests if you found an error or if</div>

<ul class="tabs clear-fix">
    <li><a class="tab-link" href="#"><u>Overview</u></a></li>
    <li><a class="tab-link active" href="#"><u>API Reference</u></a></li>
</ul>

<div class="content-wrap clear-fix">

    <div class="sidebar">

        <div class="searchbox-wrap">
            <input type="text" name="q" id="searchbox" class="searchbox" placeholder="Search"/>
            <input type="submit" class="search-button"/>
        </div>


        <ul class="api-table-of-contents">
            <li><a href="#" class="api-top-level-link">Acl</a></li>
            <li><a href="#" class="api-top-level-link">Annotations</a></li>
            <li><a href="#" class="api-top-level-link">Assets</a></li>
            <li>
                <a href="#" class="api-top-level-link active">Cache</a>
                <ul class="api-sublist dash-list">
                    <li>
                        <a class="api-link active" href="#">Backend</a>
                        <ul class="api-sublist">
                            <li><a href="#" class="api-link">Apc</a></li>
                            <li><a href="#" class="api-link">File</a></li>
                            <li><a href="#" class="api-link">Memcache</a></li>
                            <li><a href="#" class="api-link">Memory</a></li>
                            <li><a href="#" class="api-link">Mongo</a></li>
                        </ul>
                    </li>
                    <li><a class="api-link" href="#">Exeption</a></li>
                    <li>
                        <a class="api-link" href="#">Frontend</a>
                        <ul class="api-sublist">
                            <li><a href="#" class="api-link">Base64</a></li>
                            <li><a href="#" class="api-link">Data</a></li>
                            <li><a href="#" class="api-link">Json</a></li>
                            <li><a href="#" class="api-link">None</a></li>
                            <li><a href="#" class="api-link">Output</a></li>
                        </ul>
                    </li>
                    <li><a class="api-link" href="#">Multiple</a></li>
                </ul>
            </li>
            <li><a href="#" class="api-top-level-link">CLI</a></li>
            <li><a href="#" class="api-top-level-link">Config</a></li>
            <li><a href="#" class="api-top-level-link">Crypt</a></li>
            <li><a href="#" class="api-top-level-link">Db</a></li>
            <li><a href="#" class="api-top-level-link">DI</a></li>
            <li><a href="#" class="api-top-level-link">Escaper</a></li>
            <li><a href="#" class="api-top-level-link">Events</a></li>
            <li><a href="#" class="api-top-level-link">Filter</a></li>
            <li><a href="#" class="api-top-level-link">Flash</a></li>
            <li><a href="#" class="api-top-level-link">Forms</a></li>
            <li><a href="#" class="api-top-level-link">Http</a></li>
            <li><a href="#" class="api-top-level-link">Loader</a></li>
            <li><a href="#" class="api-top-level-link">Logger</a></li>
            <li><a href="#" class="api-top-level-link">Mvc</a></li>
            <li><a href="#" class="api-top-level-link">Paginator</a></li>
            <li><a href="#" class="api-top-level-link">Queue</a></li>
            <li><a href="#" class="api-top-level-link">Security</a></li>
            <li><a href="#" class="api-top-level-link">Session</a></li>
            <li><a href="#" class="api-top-level-link">Tag</a></li>
            <li><a href="#" class="api-top-level-link">Translate</a></li>
            <li><a href="#" class="api-top-level-link">Validation</a></li>
        </ul>

    </div>

    <div class="content">

        <h1><span class="lighter"><?php echo $classData['type'] ?></span> <?php echo $classData['name'] ?></h1>

        <table class="api-info-table">

            <tr>
                <th id="Namespace">Namespace:</th>
                <td><a href="#"><?php echo $classData['namespace'] ?></a></td>
            </tr>


            <?php if ( $classData['extends'] ): ?>
                <tr>
                    <th id="Extends">Extends:</th>
                    <td><a href="#"><?php echo $classData['extends'] ?></a></td>
                </tr>
            <?php endif ?>

            <?php if ( $classData['implements'] ): ?>
                <tr>
                    <th id="Implements">Implements:</th>
                    <td>
                        <?php foreach ( $classData['implements'] as $implements ): ?>
                            <a href="#"><?php echo $implements ?></a>,
                        <?php endforeach ?>
                    </td>
                </tr>
            <?php endif ?>

        </table>

        <?php if ( $classData['description'] ): ?>
            <div class="note"><?php echo $classData['description']['description'] ?></div>
        <?php endif ?>

        <!--
                <h2>Subclasses</h2>

                <ul class="two-columns">
                    <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Apc</span></a></li>
                    <li><a href="#">Phalcon\Cache\Backend\<span class="strong">File</span></a></li>
                    <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Memcache</span></a></li>
                    <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Memory</span></a></li>
                    <li><a href="#">Phalcon\Cache\Backend\<span class="strong">Mongo</span></a></li>
                </ul>
        -->
        <?php if ( $classData['constants'] ): ?>

            <h2 id="Constants">Constants</h2>

            <ul class="two-columns">
                <?php foreach ( $classData['constants'] as $value => $type ): ?>
                    <li><?php echo gettype($type) . ' ' . $value ?></li>
                <?php endforeach ?>
            </ul>

        <?php endif ?>

        <?php if ( $classData['methods'] ): ?>

            <h2 id="summary">Methods summary</h2>

            <table class="api-methods-table">
                <?php foreach ( $classData['methods'] as $method ): ?>
                    <tr>
                        <td class="method"><span class="method-type <?php echo implode(' ',$method['modifiers']) ?>" data-tooltip="public"></span> <a href="#<?php echo $method['name'] ?>"><?php echo $method['name'] ?></a></td>
                        <td class="description"><?php echo isset($method['description']['description_mini'] ) ? $method['description']['description_mini'] : '' ?></td>
                    </tr>
                <?php endforeach ?>
            </table>

            <h2 id="details">Method details</h2>

            <?php foreach ( $classData['methods'] as $method ): ?>
                <br/>
                <span class="h3" id="<?php echo $method['name'] ?>"><?php echo $method['name']; ?></span>
                <?php if($method['inherited']): ?>
                    inherited <?php echo $method['inherited'] ?>
                <?php endif ?>

                <p>
                <div class="highlight">
                    <pre><?php echo implode(' ' , $method['modifiers']) ?> <?php echo $method['name'] ?> ( <?php echo implode(', ' , $method['parameters']) ?> )</pre>
                </div>
                </p>

                <?php if ( $method['description'] ): ?>

                    <p><?php echo $method['description']['description']; ?></p>

                <?php endif ?>

                <?php if ( $method['description']['params'] ): ?>

                    <h4>Parameters:</h4>

                    <ul>
                        <?php foreach ( $method['description']['params'] as $parameterName => $parameterType ): ?>
                            <li><span class="strong"><?php echo $parameterName ?></span> <a href="#"><?php echo $parameterType ?></a></li>
                        <?php endforeach ?>
                    </ul>

                <?php endif ?>

                <?php if ( $method['description']['return'] !== 'return' ): ?>
                    <h4>Returns:</h4>

                    <p><?php echo $method['description']['return'] ?></p>
                <?php endif ?>

            <?php endforeach ?>

        <?php endif ?>
    </div>
</div>
